PeopleManagement/Controllers/AccountTransactionController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManagement.Business.AccountTransactionBusiness;
using PeopleManagement.Repository.Interface;

namespace PeopleManagement.Controllers
{
    public class AccountTransactionController : Controller
    {
        private readonly IAccountTransactionRepository _transactionRepository;
        private readonly AccountTransactionBusiness _transactionBusiness;

        public AccountTransactionController(IAccountTransactionRepository transactionRepo)
        {
            _transactionRepository = transactionRepo;
            _transactionBusiness = new AccountTransactionBusiness(_transactionRepository);
        }

        public IActionResult AccountDetails(int accountCode)
        {
            var results = _transactionBusiness.GetAccountAndTransactionInfo(accountCode);
            return View(results);
        }
    }
}

PeopleManagement/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManagement.Business.AccountsBusiness;
using PeopleManagement.Business.AccountTransactionBusiness;
using PeopleManagement.Business.PersonsBusiness;
using PeopleManagement.Repository.Interface;
using PeopleManagement.ViewModels.Accounts;

namespace PeopleManagement.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountRepository _accountRepository;
        private readonly AccountBusiness _accountBusiness;

        public AccountsController(IAccountRepository accountRepo)
        {
            _accountRepository = accountRepo;
            _accountBusiness = new AccountBusiness(_accountRepository);
        }
        public IActionResult CreateAccount(int personCode)
        {
            return View(new AccountViewModel { PersonCode = personCode});
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreateAccount(AccountViewModel accountInfo)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(accountInfo);
            }
            _accountBusiness.CreatePersonAccount(accountInfo);
            return RedirectToAction("PersonDetails", "Persons", new { personCode = accountInfo.PersonCode});
        }

        public IActionResult UpdatePersonAccount(int accountCode)
        {
            var accountInfo = _accountBusiness.GetAccountInformation(accountCode);
            return View(accountInfo);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult UpdatePersonAccount(AccountViewModel accountInfo)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(accountInfo);
            }
            _accountBusiness.UpdateAccountInformation(accountInfo);
            return RedirectToAction("PersonDetails", "Persons", new { personCode = accountInfo.PersonCode});
        }
        

        [HttpPost]
        public JsonResult CheckIfAccountExist(string accountNumber, bool isUpdate)
        {
            var exist = _accountBusiness.DoesAccountExist(accountNumber, isUpdate);
            return Json(exist);
        }
    }
}

PeopleManagement/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManagement.Business.EnumBusiness;
using PeopleManagement.Business.PersonsBusiness;
using PeopleManagement.Models.Person;
using PeopleManagement.Repository.Interface;
using X.PagedList;

namespace PeopleManagement.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IPersonRepository _personRepository;
        private readonly PersonBusiness _personBusiness;

        public PersonsController(IPersonRepository personRepo)
        {
            _personRepository = personRepo;
            _personBusiness = new PersonBusiness(_personRepository);
        }
        public IActionResult Index(int? page, string searchString)
        { 
            var results = _personBusiness.GetPersons(searchString).ToPagedList(page ?? 1, (int)PageSizeEnum.size);
            return View(results);
        }

        public IActionResult PersonDetails(int personCode)
        {
            var person = _personBusiness.GetPersonAndAccountInfo(personCode);
            return View(person);
        }


        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Edit(PersonViewModel personModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(personModel);
            }
            _personBusiness.EditPerson(personModel);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePerson(int personCode)
        {
            int affectedRows = _personBusiness.DeletePerson(personCode);
            if(affectedRows > 0) return View("Index");
            ModelState.AddModelError("", "");
            return View("Index");
        }

        public IActionResult AddPerson()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddPerson(PersonViewModel personModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(personModel);
            }
            _personBusiness.AddPerson(personModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult CheckIfPersonAlreadyExist(string idNumber, bool isUpdate)
        {
            var exist = _personBusiness.CheckIfPersonAlreadyExist(idNumber, isUpdate);
            return Json(exist);
        }

    }
}

PeopleManagement/Views/Persons/AddPerson.cshtml
@model PeopleManagement.Models.Person.PersonViewModel
@{
    ViewBag.Title = "Add New Person"; 
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Stylesheets{

}


<main class="main">
    <div class="container-fluid">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-user-plus"></i>
                <strong>Add New Person</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("AddPerson", "Persons", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "font-weight-bold" })
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control " , @style = "text-transform:uppercase" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "font-weight-bold" })
                        @Html.TextBoxFor(model => model.Surname, new { @class = "form-control " , @style = "text-transform:uppercase" })
                        @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.IdNumber, htmlAttributes: new { @class = "font-weight-bold" })
                        @Html.TextBoxFor(model => model.IdNumber, new { @class = "form-control " })
                        @Html.ValidationMessageFor(model => model.IdNumber, "", new { @class = "text-danger" })
                    </div>

                    <div>
                        <button id="submitButton" type="submit" class="btn btn-primary">Submit <i class="fa-solid fa-pen-to-square"></i></button>
                    </div>

                }

            </div>
        </div>
    </div>

</main>
@section scripts{
    
}

PeopleManagement/Views/Persons/Index.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<PeopleManagement.Models.Person.PersonViewModel>
@{ 
    ViewBag.Title = "Persons List"; 
    Layout = "~/Views/Shared/_Layout.cshtml";
    var searchString = Context.Request.Query["searchString"];
}

@section Stylesheets
{
    <link href="~/css/PagedList.css" rel="stylesheet" />
}
<div class="main">
        <div class="container-fluid">
        @using (Html.BeginForm("Index", "Persons", FormMethod.Get))
        {
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa fa-search"></i>
                    <strong>Search</strong>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="input-group">
                                @if (searchString != string.Empty)
                                {
                                    <input class="form-control" id="searchString" type="text" name="searchString" placeholder="Search by Person Surname, Id Number or Account Number." autocomplete="off" value="@searchString">
                                }
                                else
                                {
                                    <input class="form-control" id="searchString" type="text" name="searchString" placeholder="Search by Person Surname, Id Number or Account Number." autocomplete="off">
                                }
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i> Search
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

        @if (Model.Any())
        {
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> <strong>Persons List</strong>
                </div>
                
                <div class="card-body">
                    <a href="@Url.Action("AddPerson", "Persons")" class="btn btn-secondary position-relative add-btn" data-toggle="tooltip" title="Add new person">
                      <i class="fa-solid fa-user-plus"></i> New Person
                    </a>
                    <div class="table table-bordered table-striped table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">
                                        <strong>@Html.DisplayNameFor(model => model.First().Name)</strong>
                                    </th>
                                    <th class="d-none d-sm-table-cell">
                                        <strong> @Html.DisplayNameFor(model => model.First().Surname)</strong>
                                    </th>
                                    <th class="d-none d-sm-table-cell">
                                        <strong> @Html.DisplayNameFor(model => model.First().IdNumber)</strong>
                                    </th>
                                    <th>
                                        <strong>Action</strong>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var person in Model)
                                {
                                    <tr>
                                        <th scope="col">
                                            <strong>@person.Name</strong>
                                        </th>
                                        <th class="d-none d-sm-table-cell">
                                            <strong>@person.Surname</strong>
                                        </th>
                                        <th class="d-none d-sm-table-cell">
                                            <strong>@person.IdNumber</strong>
                                        </th>
                                        <th class="d-none d-sm-table-cell">
                                            <a href="@Url.Action("PersonDetails", "Persons", new {personCode = person.code})" data-toggle="tooltip" title="View or edit person"><i class="fa fa-pen"></i></a> &nbsp; &nbsp;
                                            <a href="@Url.Action("DeletePerson", "Persons", new {personCode = person.code})" data-toggle="tooltip" title="Delete @person.Name @person.Surname"><i class="fa fa-trash"></i></a>
                                        </th>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-md-12">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        }
        else
        {
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> <strong>Persons List</strong>
                </div>
                <div class="card-body">
                    <div class="alert alert-primary" role="alert">
                        <i class="fa-solid fa-circle-info"></i>
                        <text>No Records Available</text>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section scripts{
} 

PeopleManagement/Views/Persons/PersonDetails.cshtml
@using Microsoft.AspNetCore.Http
@model List<PeopleManagement.ViewModels.Persons.PersonAccountViewModel>
@{
    ViewBag.Title = "View Or Update Person Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Stylesheets{

}

<main class="main">
    <div class="container-fluid">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-circle-info"></i>
                <strong>View/Update Person and Account Data</strong>
            </div>
            <div class="card-body">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fa-solid fa-user"></i>
                        <strong>Update Personal Information</strong>
                    </div>
                    <div class="card-body">
                        @using (Html.BeginForm("Edit", "Persons", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("isUpdate", true)
                            @Html.Hidden("code", Model.First().PersonCode)

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.First().Name, htmlAttributes: new { @class = "font-weight-bold" })
                                @Html.TextBoxFor(model => model.First().Name, new { @class = "form-control " , @style = "text-transform:uppercase" })
                                @Html.ValidationMessageFor(model => model.First().Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.First().Surname, htmlAttributes: new { @class = "font-weight-bold" })
                                @Html.TextBoxFor(model => model.First().Surname, new { @class = "form-control " , @style = "text-transform:uppercase" })
                                @Html.ValidationMessageFor(model => model.First().Surname, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.First().IdNumber, htmlAttributes: new { @class = "font-weight-bold" })
                                @Html.TextBoxFor(model => model.First().IdNumber, new { @class = "form-control " })
                                @Html.ValidationMessageFor(model => model.First().IdNumber, "", new { @class = "text-danger" })
                            </div>

                            <div>
                                <button id="submitButton" type="submit" class="btn btn-primary">Update <i class="fa-solid fa-pen-to-square"></i></button>
                            </div>

                        }
                    </div>
                </div>
                <hr />

                <div class="card-body">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fa-solid fa-file-invoice-dollar"></i>
                            <strong>View/Update Account Information</strong>
                        </div>

                        <div class="card-body">
                            <a href="@Url.Action("CreateAccount", "Accounts", new{ personCode = Model?.First().PersonCode })" class="btn btn-secondary position-relative add-btn" data-toggle="tooltip" title="Add new account">
                                <i class="fa-solid fa-plus"></i> New Account
                            </a>
                            @if(Model.Any(x => x.AccountCode is null))
                            {
                                <div class="card-body account-alert">
                                    <div class="alert alert-primary" role="alert">
                                        <i class="fa-solid fa-circle-info"></i>
                                        <text>No Account Information Available</text>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="table table-bordered table-striped table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">
                                                <strong>@Html.DisplayNameFor(model => model.First().AccountNumber)</strong>
                                            </th>
                                            <th class="d-none d-sm-table-cell">
                                                <strong> @Html.DisplayNameFor(model => model.First().OustandingBalance)</strong>
                                            </th>
                                            <th>
                                                <strong>Action</strong>
                                            </th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var person in Model)
                                        {
                                            <tr>
                                                <th scope="col">
                                                    <strong>@person.AccountNumber</strong>
                                                </th>
                                                <th class="d-none d-sm-table-cell">
                                                    <strong>@person.OustandingBalance</strong>
                                                </th>
                                                <th class="d-none d-sm-table-cell">
                                                    <a href="@Url.Action("AccountDetails", "AccountTransaction", new {accountCode = person.AccountCode})" data-toggle="tooltip" title="View or edit account information"><i class="fa fa-pen"></i></a>
                                                </th>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            }
                            
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</main>
@section scripts{

}