PeopleManagement/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace PeopleManagement.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PeopleManagement/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace PeopleManagement.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PeopleManagement/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManagement.Business.EnumBusiness;
using PeopleManagement.Business.PersonsBusiness;
using PeopleManagement.Models.Person;
using PeopleManagement.Repository.Interface;
using X.PagedList;

namespace PeopleManagement.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IPersonRepository _personRepository;
        private readonly PersonBusiness _personBusiness;

        public PersonsController(IPersonRepository personRepo)
        {
            _personRepository = personRepo;
            _personBusiness = new PersonBusiness(_personRepository);
        }
        public IActionResult Index(int? page, string searchString)
        { 
            var results = _personBusiness.GetPersons(searchString).ToPagedList(page ?? 1, (int)PageSizeEnum.size);
            return View(results);
        }

        public IActionResult PersonDetails(int personCode)
        {
            var person = _personBusiness.GetPersonAndAccountInfo(personCode);
            return View(person);
        }


        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Edit(PersonViewModel personModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(personModel);
            }
            _personBusiness.EditPerson(personModel);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePerson(int personCode)
        {
            int affectedRows = _personBusiness.DeletePerson(personCode);
            if(affectedRows > 0) return View("Index");
            ModelState.AddModelError("", "");
            return View("Index");
        }

        public IActionResult AddPerson()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddPerson(PersonViewModel personModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some error occured, please try again later.");
                return View(personModel);
            }
            _personBusiness.AddPerson(personModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult CheckIfPersonAlreadyExist(string idNumber, bool isUpdate)
        {
            var exist = _personBusiness.CheckIfPersonAlreadyExist(idNumber, isUpdate);
            return Json(exist);
        }

    }
}

PeopleManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeopleManagement.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/@@coreui/coreui@4.2.0/dist/css/coreui.min.css" rel="stylesheet" integrity="sha384-UkVD+zxJKGsZP3s/JuRzapi4dQrDDuEf/kHphzg8P3v8wuQ6m9RLjTkPGeFcglQU" crossorigin="anonymous">
    @await RenderSectionAsync("Stylesheets", required: false)
</head>
<body>
        <div class="navbar">
            <a href="@Url.Action("Index", "Home")" class="logo"><img src="~/images/logoo.png" width="130px" height="100px"/></a>
            <ul>
                <li><a href="@Url.Action("Index","Home")"">Home</a></li>
                <li><a href="@Url.Action("Index","Persons")">Persons</a></li>
                <li><a href="@Url.Action("Index","About")"">About</a></li>
                <li><a href="@Url.Action("Index","Contact")"">Contact</a></li>
            </ul>
        </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://kit.fontawesome.com/d887f3087f.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@coreui/coreui@4.2.0/dist/js/coreui.bundle.min.js" integrity="sha384-n0qOYeB4ohUPebL1M9qb/hfYkTp4lvnZM6U6phkRofqsMzK29IdkBJPegsyfj/r4" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>